KahlerErrorCodes/Models/Solution.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KahlerErrorCodes.Models {
    public class Solution {
        [Key, Required, Column("id")]
        public Guid SolutionId { get; set; }
        [Required]
        public string Description { get; set; }

        public virtual IEnumerable<ErrorCodeSolution> ErrorCodeSolutions { get; set; }
    }
}

KahlerErrorCodes/Controllers/ErrorCodeSolutionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KahlerErrorCodes.DAL;
using KahlerErrorCodes.Models;

namespace KahlerErrorCodes.Controllers {
    public class ErrorCodeSolutionController : Controller {
        private ErrorCodeContext db = new ErrorCodeContext();

        [HttpGet]
        public ActionResult GetSolutions(string id, string productType, string productCode) {
            ErrorCodeSolutionResponse solution = GetSolutionsForErrorCode(db, id, productType, productCode);

            if (Request.ContentType.Equals("text/html")) {
                string htmlReturn = $"<div><dl><dt>Error</dt><dd>{solution.ErrorCode} - {solution.ErrorDescription}</dd><dt>Solutions</dt><dd>";
                if (solution.GenericSolutionsForError.Count > 0 || solution.ProductTypeSolutionsForError.Count > 0 || solution.SoftwareSpecificSolutionsForError.Count > 0) {
                    htmlReturn += $"<ul><li>{string.Join("</li><li>", solution.SoftwareSpecificSolutionsForError)}{string.Join("</li><li>", solution.ProductTypeSolutionsForError)}{string.Join("</li><li>", solution.GenericSolutionsForError)}</li></ul>";
                } else {
                    htmlReturn += "<p>No solutions defined</p>";
                }
                htmlReturn += "</dd></dl></div>";
                return Content(htmlReturn);
            } else if (Request.ContentType.Equals("text/xml") || Request.ContentType.Equals("application/xml")) {
                return Content(KaCommonObjects.XmlMethods.ToXml(solution));
            } else { // if (Request.ContentType.Equals("application/json")) {
                return Json(solution, JsonRequestBehavior.AllowGet);
            }
        }


        public ActionResult Index() {
            var errorCodeSolutions = db.ErrorCodeSolutions.Include(e => e.ErrorCode).Include(e => e.Solution);
            return View(errorCodeSolutions.ToList());
        }

        public ActionResult Details(Guid? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ErrorCodeSolution errorCodeSolution = db.ErrorCodeSolutions.Find(id);
            if (errorCodeSolution == null) {
                return HttpNotFound();
            }
            return View(errorCodeSolution);
        }

        public ActionResult Create(Guid solutionId) {
            ErrorCodeSolution errorCodeSolution = new ErrorCodeSolution() { SolutionId = solutionId };
            PopulateSolutionsDropDownList(errorCodeSolution.SolutionId);
            PopulateErrorCodesDropDownList(errorCodeSolution.ErrorCodeId);
            PopulateApplicationTypesDropDownList(errorCodeSolution.ApplicationTypeId);
            PopulateSoftwareApplicationsDropDownList(errorCodeSolution.SoftwareApplicationId);
            return View(errorCodeSolution);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SolutionId,ErrorCodeId,ApplicationTypeId,SoftwareApplicationId")] ErrorCodeSolution errorCodeSolution) {
            if (ModelState.IsValid) {
                errorCodeSolution.Id = Guid.NewGuid();
                db.ErrorCodeSolutions.Add(errorCodeSolution);
                db.SaveChanges();
                return RedirectToAction("Edit", "Solution", new { id = errorCodeSolution.SolutionId });
            }

            PopulateSolutionsDropDownList(errorCodeSolution.SolutionId);
            PopulateErrorCodesDropDownList(errorCodeSolution.ErrorCodeId);
            PopulateApplicationTypesDropDownList(errorCodeSolution.ApplicationTypeId);
            PopulateSoftwareApplicationsDropDownList(errorCodeSolution.SoftwareApplicationId);

            return View(errorCodeSolution);
        }

        public ActionResult Edit(Guid? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ErrorCodeSolution errorCodeSolution = db.ErrorCodeSolutions.Find(id);
            if (errorCodeSolution == null) {
                return HttpNotFound();
            }

            try {
                PopulateSolutionsDropDownList(errorCodeSolution.SolutionId);
                PopulateErrorCodesDropDownList(errorCodeSolution.ErrorCodeId);
                PopulateApplicationTypesDropDownList(errorCodeSolution.ApplicationTypeId);
                PopulateSoftwareApplicationsDropDownList(errorCodeSolution.SoftwareApplicationId);
            } catch (RetryLimitExceededException /* dex */) {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }
            return View(errorCodeSolution);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SolutionId,ErrorCodeId,ApplicationTypeId,SoftwareApplicationId")] ErrorCodeSolution errorCodeSolution) {
            if (ModelState.IsValid) {
                db.Entry(errorCodeSolution).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Edit", "Solution", new { id = errorCodeSolution.SolutionId });
            }
            try {
                PopulateSolutionsDropDownList(errorCodeSolution.SolutionId);
                PopulateErrorCodesDropDownList(errorCodeSolution.ErrorCodeId);
                PopulateApplicationTypesDropDownList(errorCodeSolution.ApplicationTypeId);
                PopulateSoftwareApplicationsDropDownList(errorCodeSolution.SoftwareApplicationId);
            } catch (RetryLimitExceededException /* dex */) {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }

            return View(errorCodeSolution);
        }

        public ActionResult Delete(Guid? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ErrorCodeSolution errorCodeSolution = db.ErrorCodeSolutions.Find(id);
            if (errorCodeSolution == null) {
                return HttpNotFound();
            }
            return View(errorCodeSolution);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id) {
            ErrorCodeSolution errorCodeSolution = db.ErrorCodeSolutions.Find(id);
            db.ErrorCodeSolutions.Remove(errorCodeSolution);
            db.SaveChanges();
            return RedirectToAction("Edit", "Solution", new { id = errorCodeSolution.SolutionId });
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private void PopulateSolutionsDropDownList(object selectedSolution = null) {
            ViewBag.SolutionID = new SelectList(db.Solutions.OrderBy(s => s.Description), "SolutionID", "Description", selectedSolution);
        }

        private void PopulateErrorCodesDropDownList(object selectedErrorCode = null) {
            ViewBag.ErrorCodeID = new SelectList(db.ErrorCodes.OrderBy(ec => ec.Code), "ErrorCodeID", "DisplayableName", selectedErrorCode);
        }

        private void PopulateApplicationTypesDropDownList(object selectedApplicationType = null) {
            List<ApplicationType> items = new List<ApplicationType>() { null };
            items.AddRange(db.ApplicationTypes.OrderBy(at => at.Name));
            ViewBag.ApplicationTypeID = new SelectList(items, "ApplicationTypeId", "Name", selectedApplicationType);
        }

        private void PopulateSoftwareApplicationsDropDownList(object selectedSoftwareApplication = null) {
            List<SoftwareApplication> items = new List<SoftwareApplication>() { null };
            items.AddRange(db.SoftwareApplications.OrderBy(sa => sa.Name));
            ViewBag.SoftwareApplicationID = new SelectList(items, "SoftwareApplicationID", "Name", selectedSoftwareApplication);
        }

        public static ErrorCodeSolutionResponse GetSolutionsForErrorCode(ErrorCodeContext db, string errorCode, string productType, string productCode) {
            ErrorCodeSolutionResponse solution = new ErrorCodeSolutionResponse() { SoftwareSpecificSolutionsForError = new List<string>(), ProductTypeSolutionsForError = new List<string>(), GenericSolutionsForError = new List<string>() };
            if (!string.IsNullOrWhiteSpace(errorCode)) {
                Guid errorCodeId = Guid.Empty;
                try {
                    ErrorCode ec = db.ErrorCodes.First(n => n.Code.ToLower() == errorCode.ToLower());
                    solution.ErrorCode = ec.Code;
                    solution.ErrorDescription = ec.Description;
                    errorCodeId = ec.ErrorCodeId;
                } catch (Exception) { // The error code is not found, so return an empty list 
                }
                if (!errorCodeId.Equals(Guid.Empty)) {
                    Guid applicationTypeId = Guid.Empty;
                    if (!string.IsNullOrWhiteSpace(productType)) {
                        foreach (var item in db.ApplicationTypes.Where(at => at.Name.ToLower() == productType.ToLower())) {
                            applicationTypeId = item.ApplicationTypeId;
                            break;
                        }

KahlerErrorCodes/Controllers/SolutionController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using KahlerErrorCodes.DAL;
using KahlerErrorCodes.Models;

namespace KahlerErrorCodes.Controllers {
    public class SolutionController : Controller {
        private ErrorCodeContext db = new ErrorCodeContext();

        public ActionResult Index() {
            return View(db.Solutions
                .ToList()
                .OrderBy((s) => s.Description));
        }

        public ActionResult Details(Guid? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solution solution = db.Solutions.Find(id);
            var errorCodeSolutions = db.ErrorCodeSolutions.Where(ecs => ecs.SolutionId == id.Value).ToList();
            solution.ErrorCodeSolutions = errorCodeSolutions;
            return View(solution);
        }

        public ActionResult Create() {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SolutionId,Description")] Solution solution) {
            if (ModelState.IsValid) {
                solution.SolutionId = Guid.NewGuid();

                db.Solutions.Add(solution);
                db.SaveChanges();
            }

            return View(solution);
        }

        public ActionResult Edit(Guid? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solution solution = db.Solutions.Find(id);
            if (solution == null) {
                return HttpNotFound();
            }
            solution.ErrorCodeSolutions = db.ErrorCodeSolutions.Where(ecs => ecs.SolutionId == id.Value).ToList();
            return View(solution);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SolutionId,Description")] Solution solution) {
            if (ModelState.IsValid) {
                db.Entry(solution).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(solution);
        }

        public ActionResult Delete(Guid? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solution solution = db.Solutions.Find(id);
            if (solution == null) {
                return HttpNotFound();
            }
            return View(solution);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id) {
            Solution solution = db.Solutions.Find(id);
            db.Solutions.Remove(solution);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KahlerErrorCodes/Views/Solution/Create.cshtml
@model KahlerErrorCodes.Models.Solution

@{
	ViewBag.Title = "Create solution";
}

<h2>Create solution</h2>

@using (Html.BeginForm()) {
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control col-md-8" } })
				@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
			</div>

			@*@Html.Label("Error codes", htmlAttributes: new { @class = "control-label col-md-2" })
				<table>
					<tr>
						<th>
							Error code
						</th>
						<th>
							&nbsp;
						</th>
					</tr>
					<tr>
						<td>
							&nbsp;
						</td>
						<td>
							&nbsp;
						@Html.ActionLink("Create new", "Create", "ErrorCodeSolution", new { solutionId = Model.SolutionId }, new { @class = "btn btn-info btn-sm" })
					</td>
					</tr>
					@if (Model?.ErrorCodeSolutions?.Count() > 0) {
						foreach (var modelItem in Model.ErrorCodeSolutions) {
							<tr>
								<td>
									@Html.DisplayFor(item => modelItem.ErrorCode.DisplayableName)
								</td>
								<td>
									@Html.ActionLink("Details", "Details", "ErrorCodeSolution", new { id = modelItem.Id }, new { @class = "btn btn-info btn-sm" })
									@Html.ActionLink("Edit", "Edit", "ErrorCodeSolution", new { id = modelItem.Id }, new { @class = "btn btn-info btn-sm" })
									@Html.ActionLink("Delete", "Delete", "ErrorCodeSolution", new { id = modelItem.Id }, new { @class = "btn btn-info btn-sm" })
								</td>
							</tr>
						}
					}
					</table>*@
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back", "Index", null, new { @class = "btn btn-info btn-sm" })
</div>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

KahlerErrorCodes/Views/Solution/Delete.cshtml
@model KahlerErrorCodes.Models.Solution

@{
	ViewBag.Title = "Delete solution";
}

<h2>Delete solution</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Description)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Description)
		</dd>
	</dl>

	@using (Html.BeginForm()) {
		@Html.AntiForgeryToken()

		<div class="form-actions no-color">
			<input type="submit" value="Delete" class="btn btn-default" /> |
			@Html.ActionLink("Back", "Index", null, new { @class = "btn btn-info btn-sm" })
		</div>
	}
</div>

KahlerErrorCodes/Views/Solution/Details.cshtml
@model KahlerErrorCodes.Models.Solution

@{
	ViewBag.Title = "Details";
}

<div>
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => Model.Description)
		</dt>
		<dd>
			@Html.DisplayFor(model => Model.Description)
		</dd>

		@if (Model?.ErrorCodeSolutions?.Count() > 0) {
			<dt>
				Error codes
			</dt>
			<dd>
				<ul>
					@foreach (var modelItem in Model.ErrorCodeSolutions.OrderBy(ecs => ecs.ErrorCode.Code)) {
						<li>
							@Html.DisplayFor(item => modelItem.ErrorCode.DisplayableName)
						</li>

					}
				</ul>
			</dd>
		}
	</dl>
</div>

KahlerErrorCodes/Views/Solution/Edit.cshtml
@model KahlerErrorCodes.Models.Solution

@{
	ViewBag.Title = "Solution edit";
}

<h2>Edit solution</h2>

@using (Html.BeginForm()) {
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.SolutionId)

		<div class="form-group">
			@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control col-md-12" } })
				@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
			</div>

			@Html.Label("Error codes", htmlAttributes: new { @class = "control-label col-md-2" })
			<table>
				<tr>
					<td>
						&nbsp;
					</td>
					<td>
						@Html.ActionLink("Create new", "Create", "ErrorCodeSolution", new { solutionId = Model.SolutionId }, new { @class = "btn btn-info btn-sm" })
					</td>
				</tr>
				@if (Model?.ErrorCodeSolutions?.Count() > 0) {
					foreach (var modelItem in Model.ErrorCodeSolutions.OrderBy(ecs => ecs.ErrorCode.Code)) {
						<tr>
							<td>
								@Html.DisplayFor(item => modelItem.ErrorCode.DisplayableName)
							</td>
							<td>
								@Html.ActionLink("Details", "Details", "ErrorCodeSolution", new { id = modelItem.Id }, new { @class = "btn btn-info btn-sm" }) &nbsp;
								@Html.ActionLink("Edit", "Edit", "ErrorCodeSolution", new { id = modelItem.Id }, new { @class = "btn btn-info btn-sm" }) &nbsp;
								@Html.ActionLink("Delete", "Delete", "ErrorCodeSolution", new { id = modelItem.Id }, new { @class = "btn btn-info btn-sm" })
							</td>
						</tr>
					}
				}
			</table>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Save" class="btn btn-primary py-0 px-2 fa editable fa-edit" />
			</div>
		</div>
	</div>

	<div>
		@Html.ActionLink("Back", "Index", null, new { @class = "btn btn-info btn-sm" })
	</div>
}

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

KahlerErrorCodes/Views/Solution/Index.cshtml
@model IEnumerable<KahlerErrorCodes.Models.Solution>

@{
	ViewBag.Title = "Solution index";
}

<h2>Solutions</h2>

<p>
	@Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-info btn-sm" })
</p>
<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Description)
		</th>
		<th>
			&nbsp;
		</th>
	</tr>

	@foreach (var item in Model) {
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Description)
			</td>
			<td>
				@Html.ActionLink("Details", "Details", new { id = item.SolutionId }, new { @class = "btn btn-info btn-sm" })
				@Html.ActionLink("Edit", "Edit", new { id = item.SolutionId }, new { @class = "btn btn-info btn-sm" })
				@Html.ActionLink("Delete", "Delete", new { id = item.SolutionId }, new { @class = "btn btn-info btn-sm" })
			</td>
		</tr>
	}
</table>